### ISSUE TITLE
Problem with `template`: children should not be mutated in `constructor` (specs)

### ISSUE THREAD

**Issue by guitarino** [WebReflection/dom-class#4]
Hi Andrea,

I noticed that, when bindings or `template` is used, the element's content is mutated during element's creation phase (in the constructor). However, the [specs](https://html.spec.whatwg.org/multipage/scripting.html#custom-element-conformance) say the following:

**4.13.2 Requirements for custom element constructors**
- The element must not gain any attributes or children, as this violates the expectations of consumers who use the createElement or createElementNS methods.
- In general, work should be deferred to connectedCallback as much as possible—especially work involving fetching resources or rendering. However, note that connectedCallback can be called more than once, so any initialization work that is truly one-time will need a guard to prevent it from running twice.
- In general, the constructor should be used to set up initial state and default values, and to set up event listeners and possibly a shadow root.

It appears that, according to specs, a better place to trigger DOM changes (including applying the template) would be in the `connectedCallback`, i.e. `onAttached` method of `DOMClass` element.

Here's the simplest use-case
```javascript
var TestBindings = DOMClass({
  name: 'test-binding',
  with: [DOMClass.bindings],
  template: '<div>Some html</div>',
  constructor: function() {
      console.log('constructor', this.outerHTML);
  },
  onAttached: function() {
      console.log('onAttached', this.outerHTML);
  }
});
document.body.appendChild(document.createElement('test-binding'));
```

The current console output is
```
constructor <test-binding><div>Some html</div></test-binding>
onAttached <test-binding><div>Some html</div></test-binding>
```

The expected output is
```
constructor <test-binding></test-binding>
onAttached <test-binding><div>Some html</div></test-binding>
```

Unfortunately, that could be a breaking change for some elements, but that's what specs require.

**Comment by WebReflection** [comment]
Sorry I’m a bit late to notice, or answer, this issue, thanks for closing it.

As I’ve created much better alternatives, I think the best thing to do is to archive this repository, as anything in here is better covered by wickedElements or hookedElements.

I have no plans to keep maintaining this outdated idea, so I hope this makes sense.
